### ISSUE TITLE
serial.serialutil.SerialException: could not open port 'COM10' 

### ISSUE THREAD

**Issue by HannesDampft** [0x6AB/BDO_fisher#1]
Hey there,

i get the Same Problem whether i use the compiled Version or try it with python and all dependencys installed:

started new process
[space]
Process Process-1:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "main.py", line 238, in main
  File "CustomKeyboard.py", line 14, in __init__
  File "serial\serialwin32.py", line 33, in __init__
  File "serial\serialutil.py", line 244, in __init__
  File "serial\serialwin32.py", line 64, in open
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden.', None, 2)
Exception ignored in: <function CustomKeyboard.__del__ at 0x12E1CA48>
Traceback (most recent call last):
  File "CustomKeyboard.py", line 20, in __del__
AttributeError: 'NoneType' object has no attribute 'close'
started new process
[space]
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "main.py", line 238, in main
  File "CustomKeyboard.py", line 14, in __init__
  File "serial\serialwin32.py", line 33, in __init__
  File "serial\serialutil.py", line 244, in __init__
  File "serial\serialwin32.py", line 64, in open
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'Das System kann die angegebene Datei nicht finden.', None, 2)
Exception ignored in: <function CustomKeyboard.__del__ at 0x13AACA48>
Traceback (most recent call last):
  File "CustomKeyboard.py", line 20, in __del__
AttributeError: 'NoneType' object has no attribute 'close'
started new process

What Version of Python do you use? i used: Python 3.9.0

**Comment by 0x6AB** [comment]
To use the bot, you need a "Hardware Dongle" that will emulate the keyboard. It is he who uses the COM port.
See this repository: https://github.com/0x6AB/CustomKeyboard_Teensy, need arduino leonardo or any other "arduino-compatible" device based on ATmega32U4.
Software emulation is currently not supported because it is not secure.
